---
name: Jeffrey Y Lee
# surname: Lee
date: "`r format(Sys.time(), '%B, %Y')`"
#qualifications: 
address: "University of Glasgow, G12 8QQ, UK"
position: "Postdoctoral scientist"
# profilepic: FOTO.png
# phone: 0996597844
email: "Jeff.Lee@glasgow.ac.uk"
orcid: "0000-0002-5146-0037"
googlescholar: "Scholar"
github: GitHub
linkedin: Linkedin
twitter: Twitter/X
# www: darwincubi.rbind.io
# header-includes:
headcolor: 3B9DE1
output: 
  vitae::awesomecv:
    page_total: true
    pandoc_args:
      - --lua-filter="/Users/jefflee/Documents/Github/JeffYLee_CV/2023_late/lua/strong.lua"
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(dplyr)
library(magrittr)
source("Utils/data_download_funs.R") 

CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1WPoKQiKZWfyvW5HA48tUJ1JOth7A2-Vb0v6HsmcmUSs/edit?usp=sharing",  
  pdf_mode = FALSE
)

```

\vspace*{0.5cm}

```{r, results='asis'}
CV %<>% print_text_block("intro") 
```

# Employment

```{r}
CV$entries_data %>% 
  filter(section == 'employment') %>% 
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`} - {`end`}"),
    with = title,
    where = loc,
    why = description_bullets
  )
```

# Education

```{r}
CV$entries_data %>% 
  filter(section == 'education') %>% 
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`} - {`end`}"),
    with = title,
    where = loc,
    why = description_bullets
  )
```

# Skills

```{r, results='asis'}
CV %>% print_skill()
```

# Publications

\scriptsize

## Lead author publications

```{r}
library(dplyr)
# knitr::write_bib(c("vitae", "tibble"), "Lead_pub.bib")

# bibliography_entries("Lead_pub.bib") %>%
#   arrange(desc(issued))
# 
# 
# 

```

&nbsp;

## Contributing publications

```{r, results = "asis"}
library(dplyr)
library(stringr)
library(scholar)
# knitr::write_bib(c("vitae", "tibble"), "Contributing_pub.bib")

# bibliography_entries("Contributing_pub.bib") %>%
#   arrange(desc(issued))

# CV$contributing_pub %>%
#   # mutate(author = str_replace(author, "Lee, J. Y.", "\\\\textbf{Lee, J. Y.}")) %>%
#   tibble::new_tibble(preserve = "id", class = c("vitae_bibliography",
#     "vitae_preserve"), nrow = nrow(CV$contributing_pub))


format.authors <- function(scholar.profile, author.name) {
  library(dplyr)

  swap_initials <- function(author.name) {
    sub("(.*) (.*)", "\\2, \\1.", trimws(author.name))
  }

  pubs <- scholar::get_publications(scholar.profile)
  pubs %>%
    strsplit(x = .$author, split = ",") -> pubs2
  lapply(pubs2, function(x) {
    x <- swap_initials(x)
    x[length(x)] <- paste0("& ", x[length(x)])
    x <- paste0(x, collapse = ", ")
    ifelse(startsWith(x, "& "), sub("& ", "", x), x)
    }
    ) -> pubs$author

  author.name2 <- swap_initials(author.name)

  pubs %>%
    arrange(desc(year)) %>%
    mutate(journal = paste0("*", journal, "*"),
           Publications = paste0(author, " (", year, "). ",
                                 title, ". ", journal, ". ",
                                 number),
           Publications = gsub(author.name2, paste0("**", author.name2, "**"), Publications)) %>%
    select(Publications)
}

pubs <- format.authors("CxsNxLsAAAAJ", "JY Lee")

cat(unlist(pubs), sep = "\\\n \\\n")

```

\normalsize

# Professional service 

```{r}
CV$entries_data %>% 
  filter(section == 'serv') %>% 
  arrange(desc(start)) %>%
  detailed_entries(
    what = institution,
    with = title,
    why = description_bullets
  )
```

# Teaching 

```{r}
CV$entries_data %>% 
  filter(section == 'teaching') %>% 
  arrange(desc(start)) %>%
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`} - {`end`}"),
    with = title,
  )
```

# Certificates & Awards

```{r}
CV$entries_data %>% 
  filter(section == 'cert') %>% 
  arrange(desc(start)) %>%
  brief_entries(
    what = title,
    when = start,
    with = institution,
  )
```

# Pre-PhD employment

```{r}
CV$entries_data %>% 
  filter(section == 'prephd_employment') %>% 
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`} - {`end`}"),
    with = title,
    why = description_bullets
  )
```








