---
name: Jeffrey Y Lee
# surname: Lee
date: "`r format(Sys.time(), '%B, %Y')`"
#qualifications: 
address: "University of Oxford, OX1 3QU, UK"
position: "Postdoctoral scientist"
# profilepic: FOTO.png
# phone: 0996597844
email: "jeff.lee@bioch.ox.ac.uk"
orcid: "0000-0002-5146-0037"
googlescholar: "Scholar"
github: jefflee1103
linkedin: jeffyslee
twitter: jefflee1103
# www: darwincubi.rbind.io
# header-includes:
headcolor: 3B9DE1
output: 
  vitae::awesomecv:
    page_total: true
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(dplyr)
library(magrittr)
source("Utils/data_download_funs.R")

CV <- create_CV_object(
  data_location = "https://docs.google.com/spreadsheets/d/1WPoKQiKZWfyvW5HA48tUJ1JOth7A2-Vb0v6HsmcmUSs/edit?usp=sharing",  
  pdf_mode = FALSE
)

```

\vspace*{0.5cm}

```{r, results='asis'}
CV %<>% print_text_block("intro") 
```

# Employment

```{r}
CV$entries_data %>% 
  filter(section == 'employment') %>% 
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`} - {`end`}"),
    with = title,
    where = loc,
    why = description_bullets
  )
```

# Education

```{r}
CV$entries_data %>% 
  filter(section == 'education') %>% 
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`} - {`end`}"),
    with = title,
    where = loc,
    why = description_bullets
  )
```

# Skills

```{r, results='asis'}
CV %>% print_skill()
```

# Publications

## Lead author publications

```{r}
library(dplyr)
# knitr::write_bib(c("vitae", "tibble"), "Lead_pub.bib")

bibliography_entries("Lead_pub.bib") %>%
  arrange(desc(issued))
```

&nbsp;

## Contributing publications

```{r}
library(dplyr)
# knitr::write_bib(c("vitae", "tibble"), "Contributing_pub.bib")

bibliography_entries("Contributing_pub.bib") %>%
  arrange(desc(issued))
```

# Professional service 

```{r}
CV$entries_data %>% 
  filter(section == 'serv') %>% 
  arrange(desc(start)) %>%
  detailed_entries(
    what = institution,
    with = title,
    why = description_bullets
  )
```

# Teaching 

```{r}
CV$entries_data %>% 
  filter(section == 'teaching') %>% 
  arrange(desc(start)) %>%
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`} - {`end`}"),
    with = title,
  )
```

# Certificates & Awards

```{r}
CV$entries_data %>% 
  filter(section == 'cert') %>% 
  arrange(desc(start)) %>%
  brief_entries(
    what = title,
    when = start,
    with = institution,
  )
```

# Pre-PhD employment

```{r}
CV$entries_data %>% 
  filter(section == 'prephd_employment') %>% 
  detailed_entries(
    what = institution,
    when = glue::glue("{`start`} - {`end`}"),
    with = title,
    why = description_bullets
  )
```








